### ISSUE TITLE
Change check-box to "disable add-ons"

### ISSUE THREAD

**Issue by levansy2020** [angelleye/woocommerce-product-addons-variable#5]
Go ahead and leave the product add-ons displayed by default, and our check-box would be to "disable add-ons". So that way people would only have to go in and disable it on the ones they don't want it showing up on.

I think in most cases people would want add-ons to show up.  Just some of the unique cases where a particular variation doesn't make sense to show them.

**Comment by angelleye** [comment]
I've pulled this change and uploaded to my server, but I'm not getting expected results.

First, I see that the option still says "Display add-ons" but the tool-tip does say "Disable Product Add-Ons".  The option label itself needs to say "Disable Product Add-Ons" too.

![image](https://cloud.githubusercontent.com/assets/629241/9898294/b826ef46-5c16-11e5-9661-11bed956adbe.png)

That said, the check box setting itself doesn't seem to be doing anything for me.  When I load a variable product with add-ons, they get hidden by default (which it shouldn't do after this issue was completed) and it doesn't show up at all whether I have the option box checked or not.
